### ISSUE TITLE
Files are generated in incorrect submodule when package name contains `.`

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/persist-tools#273]
**Description:**
If the package name contains `.` like `patient.scheduling` and persist feature is initialized to generate the files in submodule named `db`. The `Ballerina.toml` configures are as follows,

```toml
[package]
org = "danesh"
name = "patient.scheduling"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "patient.scheduling.db"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.0.0"
```

Files are generated inside `scheduling` submodule inside the generated directory.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
